### ISSUE TITLE
Document benefit of this project

### ISSUE THREAD

**Issue by helmbold** [quarkiverse/quarkus-jdbi#45]
From looking at the [start page](https://github.com/quarkiverse/quarkus-jdbi) of this repository it is not clear to me, what this project would simplify compared to pulling the JDBI library directly. 

It would be nice if the documentation would describe the **advantages of quarkus-jdbi** and if there would be a little **example** how it would be used with Quarkus (not explaining JDBI as such).

**Comment by smil2k** [comment]
Thank you for your insight.

Currently the only benefit, that native image generation works:-)
